-- ============================================================
-- COURTS REGISTER: REPLACE HAND-TYPED SEED WITH SOURCED DATA
--
-- Migration 025 seeded the `courts` table with ~95 rows written by hand
-- from general knowledge of the court system. This replaces that seed
-- with 326 rows sourced from the Judiciary of Kenya / Office of the
-- Registrar Magistrates' Court (ormc.judiciary.go.ke), including the full
-- 224-entry subordinate court list migration 025 did not have at all.
-- The raw source files are kept in the repo at
-- src/data/kenya-judiciary/*.json for provenance and future reseeding.
--
-- Zero legal_matters rows reference a court_id yet (verified before writing
-- this migration), so the old rows are safe to remove outright rather than
-- needing a soft-delete/merge.
-- ============================================================

DELETE FROM courts;

INSERT INTO courts (name, court_type, is_superior, station, county, notes, is_active, display_order) VALUES
('Supreme Court of Kenya', 'supreme', true, 'Nairobi', 'Nairobi', 'The Supreme Court sits only in Nairobi; it is not decentralised.', true, 1),
('Court of Appeal', 'court_of_appeal', true, 'Nairobi', 'Nairobi', 'Main registry.', true, 2),
('Court of Appeal', 'court_of_appeal', true, 'Mombasa', 'Mombasa', 'Main registry.', true, 3),
('Court of Appeal', 'court_of_appeal', true, 'Nakuru', 'Nakuru', 'Main registry.', true, 4),
('Court of Appeal', 'court_of_appeal', true, 'Nyeri', 'Nyeri', 'Main registry.', true, 5),
('Court of Appeal', 'court_of_appeal', true, 'Kisumu', 'Kisumu', 'Main registry.', true, 6),
('Court of Appeal', 'court_of_appeal', true, 'Eldoret', 'Uasin Gishu', 'Main registry.', true, 7),
('Court of Appeal', 'court_of_appeal', true, 'Malindi', NULL, 'Sub-registry.', true, 8),
('Court of Appeal', 'court_of_appeal', true, 'Garissa', 'Garissa', 'Sub-registry.', true, 9),
('Court of Appeal', 'court_of_appeal', true, 'Kisii', 'Kisii', 'Sub-registry.', true, 10),
('Court of Appeal', 'court_of_appeal', true, 'Busia', 'Busia', 'Sub-registry.', true, 11),
('Court of Appeal', 'court_of_appeal', true, 'Meru', 'Meru', 'Listed on the Court of Appeal contact page; registry/circuit status not confirmed at time of seeding. Verify before use.', false, 12),
('Court of Appeal', 'court_of_appeal', true, 'Kakamega', 'Kakamega', 'Listed on the Court of Appeal contact page; registry/circuit status not confirmed at time of seeding. Verify before use.', false, 13),
('High Court of Kenya', 'high_court', true, 'Bomet', 'Bomet', NULL, true, 14),
('High Court of Kenya', 'high_court', true, 'Bungoma', 'Bungoma', NULL, true, 15),
('High Court of Kenya', 'high_court', true, 'Busia', 'Busia', NULL, true, 16),
('High Court of Kenya', 'high_court', true, 'Chuka', 'Tharaka-Nithi', NULL, true, 17),
('High Court of Kenya', 'high_court', true, 'Eldoret', 'Uasin Gishu', NULL, true, 18),
('High Court of Kenya', 'high_court', true, 'Embu', 'Embu', NULL, true, 19),
('High Court of Kenya', 'high_court', true, 'Garissa', 'Garissa', NULL, true, 20),
('High Court of Kenya', 'high_court', true, 'Garsen', NULL, NULL, true, 21),
('High Court of Kenya', 'high_court', true, 'Homabay', NULL, NULL, true, 22),
('High Court of Kenya', 'high_court', true, 'Kabarnet', 'Baringo', NULL, true, 23),
('High Court of Kenya', 'high_court', true, 'Kajiado', 'Kajiado', NULL, true, 24),
('High Court of Kenya', 'high_court', true, 'Kakamega', 'Kakamega', NULL, true, 25),
('High Court of Kenya', 'high_court', true, 'Kapenguria', 'West Pokot', NULL, true, 26),
('High Court of Kenya', 'high_court', true, 'Kericho', 'Kericho', NULL, true, 27),
('High Court of Kenya', 'high_court', true, 'Kerugoya', NULL, NULL, true, 28),
('High Court of Kenya', 'high_court', true, 'Kiambu', 'Kiambu', NULL, true, 29),
('High Court of Kenya', 'high_court', true, 'Kibera', NULL, NULL, true, 30),
('High Court of Kenya', 'high_court', true, 'Kisii', 'Kisii', NULL, true, 31),
('High Court of Kenya', 'high_court', true, 'Kisumu', 'Kisumu', NULL, true, 32),
('High Court of Kenya', 'high_court', true, 'Kitale', 'Trans-Nzoia', NULL, true, 33),
('High Court of Kenya', 'high_court', true, 'Kitui', 'Kitui', NULL, true, 34),
('High Court of Kenya', 'high_court', true, 'Kwale', 'Kwale', NULL, true, 35),
('High Court of Kenya', 'high_court', true, 'Lodwar', 'Turkana', NULL, true, 36),
('High Court of Kenya', 'high_court', true, 'Machakos', 'Machakos', NULL, true, 37),
('High Court of Kenya', 'high_court', true, 'Makueni', 'Makueni', NULL, true, 38),
('High Court of Kenya', 'high_court', true, 'Malindi', NULL, NULL, true, 39),
('High Court of Kenya', 'high_court', true, 'Marsabit', 'Marsabit', NULL, true, 40),
('High Court of Kenya', 'high_court', true, 'Meru', 'Meru', NULL, true, 41),
('High Court of Kenya', 'high_court', true, 'Migori', 'Migori', NULL, true, 42),
('High Court of Kenya', 'high_court', true, 'Mombasa', 'Mombasa', NULL, true, 43),
('High Court of Kenya', 'high_court', true, 'Murang''a', 'Murang''a', NULL, true, 44),
('High Court of Kenya', 'high_court', true, 'Nairobi', 'Nairobi', NULL, true, 45),
('High Court of Kenya', 'high_court', true, 'Naivasha', NULL, NULL, true, 46),
('High Court of Kenya', 'high_court', true, 'Nakuru', 'Nakuru', NULL, true, 47),
('High Court of Kenya', 'high_court', true, 'Nanyuki', NULL, NULL, true, 48),
('High Court of Kenya', 'high_court', true, 'Narok', 'Narok', NULL, true, 49),
('High Court of Kenya', 'high_court', true, 'Nyahururu', NULL, NULL, true, 50),
('High Court of Kenya', 'high_court', true, 'Nyamira', 'Nyamira', NULL, true, 51),
('High Court of Kenya', 'high_court', true, 'Nyandarua', 'Nyandarua', NULL, true, 52),
('High Court of Kenya', 'high_court', true, 'Nyeri', 'Nyeri', NULL, true, 53),
('High Court of Kenya', 'high_court', true, 'Siaya', 'Siaya', NULL, true, 54),
('High Court of Kenya', 'high_court', true, 'Thika', NULL, NULL, true, 55),
('High Court of Kenya', 'high_court', true, 'Vihiga', 'Vihiga', NULL, true, 56),
('High Court of Kenya', 'high_court', true, 'Voi', 'Taita-Taveta', NULL, true, 57),
('Environment and Land Court', 'elc', true, 'Bomet', 'Bomet', 'Status of the High Court.', true, 58),
('Environment and Land Court', 'elc', true, 'Busia', 'Busia', 'Status of the High Court.', true, 59),
('Environment and Land Court', 'elc', true, 'Eldoret', 'Uasin Gishu', 'Status of the High Court.', true, 60),
('Environment and Land Court', 'elc', true, 'Embu', 'Embu', 'Status of the High Court.', true, 61),
('Environment and Land Court', 'elc', true, 'Homa Bay', 'Homa Bay', 'Status of the High Court.', true, 62),
('Environment and Land Court', 'elc', true, 'Isiolo', 'Isiolo', 'Status of the High Court.', true, 63),
('Environment and Land Court', 'elc', true, 'Kabarnet', 'Baringo', 'Status of the High Court.', true, 64),
('Environment and Land Court', 'elc', true, 'Kajiado', 'Kajiado', 'Status of the High Court.', true, 65),
('Environment and Land Court', 'elc', true, 'Kakamega', 'Kakamega', 'Status of the High Court.', true, 66),
('Environment and Land Court', 'elc', true, 'Kericho', 'Kericho', 'Status of the High Court.', true, 67),
('Environment and Land Court', 'elc', true, 'Kerugoya', NULL, 'Status of the High Court.', true, 68),
('Environment and Land Court', 'elc', true, 'Kisumu', 'Kisumu', 'Status of the High Court.', true, 69),
('Environment and Land Court', 'elc', true, 'Kitale', 'Trans-Nzoia', 'Status of the High Court.', true, 70),
('Environment and Land Court', 'elc', true, 'Kwale', 'Kwale', 'Status of the High Court.', true, 71),
('Environment and Land Court', 'elc', true, 'Machakos', 'Machakos', 'Status of the High Court.', true, 72),
('Environment and Land Court', 'elc', true, 'Malindi', NULL, 'Status of the High Court.', true, 73),
('Environment and Land Court', 'elc', true, 'Meru', 'Meru', 'Status of the High Court.', true, 74),
('Environment and Land Court', 'elc', true, 'Mombasa', 'Mombasa', 'Status of the High Court.', true, 75),
('Environment and Land Court', 'elc', true, 'Nairobi', 'Nairobi', 'Status of the High Court.', true, 76),
('Environment and Land Court', 'elc', true, 'Naivasha', NULL, 'Status of the High Court.', true, 77),
('Environment and Land Court', 'elc', true, 'Nakuru', 'Nakuru', 'Status of the High Court.', true, 78),
('Environment and Land Court', 'elc', true, 'Nanyuki', NULL, 'Status of the High Court.', true, 79),
('Environment and Land Court', 'elc', true, 'Narok', 'Narok', 'Status of the High Court.', true, 80),
('Environment and Land Court', 'elc', true, 'Nyahururu', NULL, 'Status of the High Court.', true, 81),
('Environment and Land Court', 'elc', true, 'Nyandarua', 'Nyandarua', 'Status of the High Court.', true, 82),
('Environment and Land Court', 'elc', true, 'Nyeri', 'Nyeri', 'Status of the High Court.', true, 83),
('Environment and Land Court', 'elc', true, 'Siaya', 'Siaya', 'Status of the High Court.', true, 84),
('Environment and Land Court', 'elc', true, 'Thika', NULL, 'Status of the High Court.', true, 85),
('Environment and Land Court', 'elc', true, 'Vihiga', 'Vihiga', 'Status of the High Court.', true, 86),
('Environment and Land Court', 'elc', true, 'Voi', 'Taita-Taveta', 'Status of the High Court.', true, 87),
('Employment and Labour Relations Court', 'elrc', true, 'Nairobi', 'Nairobi', 'Status of the High Court.', true, 88),
('Employment and Labour Relations Court', 'elrc', true, 'Mombasa', 'Mombasa', 'Status of the High Court.', true, 89),
('Employment and Labour Relations Court', 'elrc', true, 'Kisumu', 'Kisumu', 'Status of the High Court.', true, 90),
('Employment and Labour Relations Court', 'elrc', true, 'Nakuru', 'Nakuru', 'Status of the High Court.', true, 91),
('Employment and Labour Relations Court', 'elrc', true, 'Kericho', 'Kericho', 'Status of the High Court.', true, 92),
('Employment and Labour Relations Court', 'elrc', true, 'Nyeri', 'Nyeri', 'Status of the High Court.', true, 93),
('Employment and Labour Relations Court', 'elrc', true, 'Eldoret', 'Uasin Gishu', 'Status of the High Court.', true, 94),
('Employment and Labour Relations Court', 'elrc', true, 'Kakamega', 'Kakamega', 'Status of the High Court.', true, 95),
('Employment and Labour Relations Court', 'elrc', true, 'Malindi', NULL, 'Status of the High Court.', true, 96),
('Employment and Labour Relations Court', 'elrc', true, 'Machakos', 'Machakos', 'Status of the High Court.', true, 97),
('Employment and Labour Relations Court', 'elrc', true, 'Bungoma', 'Bungoma', 'Status of the High Court.', true, 98),
('Employment and Labour Relations Court', 'elrc', true, 'Garissa', 'Garissa', 'Status of the High Court.', true, 99),
('Employment and Labour Relations Court', 'elrc', true, 'Kisii', 'Kisii', 'Status of the High Court.', true, 100),
('Employment and Labour Relations Court', 'elrc', true, 'Voi', 'Taita-Taveta', 'Status of the High Court.', true, 101),
('Employment and Labour Relations Court', 'elrc', true, 'Kitale', 'Trans-Nzoia', 'Status of the High Court.', true, 102),
('Employment and Labour Relations Court', 'elrc', true, 'Meru', 'Meru', 'Status of the High Court.', true, 103),
('Bungoma Law Courts', 'magistrate', false, 'Bungoma', 'Bungoma', NULL, true, 104),
('Bungoma Kadhis Court', 'kadhi', false, 'Bungoma', 'Bungoma', NULL, true, 105),
('Webuye Law Courts', 'magistrate', false, 'Bungoma', 'Bungoma', NULL, true, 106),
('Kimilili Law Courts', 'magistrate', false, 'Bungoma', 'Bungoma', NULL, true, 107),
('Sirisia Law Courts', 'magistrate', false, 'Bungoma', 'Bungoma', NULL, true, 108),
('Busia Law Courts', 'magistrate', false, 'Busia', 'Busia', NULL, true, 109),
('Busia SCC', 'small_claims', false, 'Busia', 'Busia', NULL, true, 110),
('Malaba Law Courts', 'magistrate', false, 'Busia', 'Busia', NULL, true, 111),
('Malaba SCC', 'small_claims', false, 'Busia', 'Busia', NULL, true, 112),
('Port Victoria Law Courts', 'magistrate', false, 'Busia', 'Busia', NULL, true, 113),
('Eldoret Law Courts', 'magistrate', false, 'Eldoret', 'Uasin Gishu', NULL, true, 114),
('Eldoret Kadhis Court', 'kadhi', false, 'Eldoret', 'Uasin Gishu', NULL, true, 115),
('Eldoret SCC', 'small_claims', false, 'Eldoret', 'Uasin Gishu', NULL, true, 116),
('Moiben Law Courts', 'magistrate', false, 'Eldoret', 'Uasin Gishu', NULL, true, 117),
('Kapsabet Law Courts', 'magistrate', false, 'Eldoret', 'Nandi', NULL, true, 118),
('Kabiyet Law Courts', 'magistrate', false, 'Eldoret', 'Nandi', NULL, true, 119),
('Tinderet Law Courts', 'magistrate', false, 'Eldoret', 'Nandi', NULL, true, 120),
('Iten Law Courts', 'magistrate', false, 'Eldoret', 'Elgeyo-Marakwet', NULL, true, 121),
('Embu Law Courts', 'magistrate', false, 'Embu', 'Embu', NULL, true, 122),
('Embu SCC', 'small_claims', false, 'Embu', 'Embu', NULL, true, 123),
('Runyenjes Law Courts', 'magistrate', false, 'Embu', 'Embu', NULL, true, 124),
('Siakago Law Courts', 'magistrate', false, 'Embu', 'Embu', NULL, true, 125),
('Garissa Law Courts', 'magistrate', false, 'Garissa', 'Garissa', NULL, true, 126),
('Garissa Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 127),
('Daadab Law Courts', 'magistrate', false, 'Garissa', 'Garissa', NULL, true, 128),
('Dadaab Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 129),
('Dadaab SCC', 'small_claims', false, 'Garissa', 'Garissa', NULL, true, 130),
('Balambala Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 131),
('Elwak Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 132),
('Ijara Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 133),
('Modogashe Kadhis Court - subregistry', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 134),
('Bura/Fafi Kadhis Court - subregistry', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 135),
('Witu Kadhis Court', 'kadhi', false, 'Garissa', 'Garissa', NULL, true, 136),
('Wajir Law Courts', 'magistrate', false, 'Garissa', 'Wajir', NULL, true, 137),
('Wajir Kadhis Court', 'kadhi', false, 'Garissa', 'Wajir', NULL, true, 138),
('Wajir SCC', 'small_claims', false, 'Garissa', 'Wajir', NULL, true, 139),
('Bute Kadhis Court', 'kadhi', false, 'Garissa', 'Wajir', NULL, true, 140),
('Eldas Kadhis Court', 'kadhi', false, 'Garissa', 'Wajir', NULL, true, 141),
('Habaswein Kadhis Court', 'kadhi', false, 'Garissa', 'Wajir', NULL, true, 142),
('Mandera Law Courts', 'magistrate', false, 'Garissa', 'Mandera', NULL, true, 143),
('Mandera Kadhis Court', 'kadhi', false, 'Garissa', 'Mandera', NULL, true, 144),
('Mandera SCC', 'small_claims', false, 'Garissa', 'Mandera', NULL, true, 145),
('Takaba Kadhis Court', 'kadhi', false, 'Garissa', 'Mandera', NULL, true, 146),
('Homabay Law Courts', 'magistrate', false, 'Homabay', 'Homa Bay', NULL, true, 147),
('Mbita Law Courts', 'magistrate', false, 'Homabay', 'Homa Bay', NULL, true, 148),
('Oyugis Law Courts', 'magistrate', false, 'Homabay', 'Homa Bay', NULL, true, 149),
('Kendu Bay Law Courts', 'magistrate', false, 'Homabay', 'Homa Bay', NULL, true, 150),
('Ndhiwa Law Courts', 'magistrate', false, 'Homabay', 'Homa Bay', NULL, true, 151),
('Kakamega Law Courts', 'magistrate', false, 'Kakamega', 'Kakamega', NULL, true, 152),
('Kakamega Kadhis Court', 'kadhi', false, 'Kakamega', 'Kakamega', NULL, true, 153),
('Kakamega SCC', 'small_claims', false, 'Kakamega', 'Kakamega', NULL, true, 154),
('Mumias Law Courts', 'magistrate', false, 'Kakamega', 'Kakamega', NULL, true, 155),
('Butere Law Courts', 'magistrate', false, 'Kakamega', 'Kakamega', NULL, true, 156),
('Butali Law Courts', 'magistrate', false, 'Kakamega', 'Kakamega', NULL, true, 157),
('Vihiga Law Courts', 'magistrate', false, 'Vihiga', 'Vihiga', NULL, true, 158),
('Hamisi Law Courts', 'magistrate', false, 'Vihiga', 'Vihiga', NULL, true, 159),
('Kericho Law Courts', 'magistrate', false, 'Kericho', 'Kericho', NULL, true, 160),
('Kericho Kadhis Court', 'kadhi', false, 'Kericho', 'Kericho', NULL, true, 161),
('Kericho SCC', 'small_claims', false, 'Kericho', 'Kericho', NULL, true, 162),
('Bomet Law Courts', 'magistrate', false, 'Bomet', 'Bomet', NULL, true, 163),
('Sotik Law Courts', 'magistrate', false, 'Bomet', 'Bomet', NULL, true, 164),
('Kerugoya Law Courts', 'magistrate', false, 'Kerugoya', 'Kirinyaga', NULL, true, 165),
('Kerugoya SCC', 'small_claims', false, 'Kerugoya', 'Kirinyaga', NULL, true, 166),
('Baricho Law Courts', 'magistrate', false, 'Kerugoya', 'Kirinyaga', NULL, true, 167),
('Gichugu Law Courts', 'magistrate', false, 'Kerugoya', 'Kirinyaga', NULL, true, 168),
('Wang''uru Law Courts', 'magistrate', false, 'Kerugoya', 'Kirinyaga', NULL, true, 169),
('Kitale Law Courts', 'magistrate', false, 'Kitale', 'Trans Nzoia', NULL, true, 170),
('Kitale SCC', 'small_claims', false, 'Kitale', 'Trans Nzoia', NULL, true, 171),
('Lodwar Law Courts', 'magistrate', false, 'Lodwar', 'Turkana', NULL, true, 172),
('Kakuma Law Courts', 'magistrate', false, 'Lodwar', 'Turkana', NULL, true, 173),
('Kakuma Kadhis Court', 'kadhi', false, 'Lodwar', 'Turkana', NULL, true, 174),
('Kakuma SCC', 'small_claims', false, 'Lodwar', 'Turkana', NULL, true, 175),
('Kapenguria Law Courts', 'magistrate', false, 'Kapenguria', 'West Pokot', NULL, true, 176),
('Kisii Law Courts', 'magistrate', false, 'Kisii', 'Kisii', NULL, true, 177),
('Kisii SCC', 'small_claims', false, 'Kisii', 'Kisii', NULL, true, 178),
('Ogembo Law Courts', 'magistrate', false, 'Kisii', 'Kisii', NULL, true, 179),
('Etago Law Courts', 'magistrate', false, 'Kisii', 'Kisii', NULL, true, 180),
('Nyamira Law Courts', 'magistrate', false, 'Nyamira', 'Nyamira', NULL, true, 181),
('Keroka Law Courts', 'magistrate', false, 'Nyamira', 'Nyamira', NULL, true, 182),
('Narok Law Courts', 'magistrate', false, 'Narok', 'Narok', NULL, true, 183),
('Narok SCC', 'small_claims', false, 'Narok', 'Narok', NULL, true, 184),
('Kilgoris Law Courts', 'magistrate', false, 'Narok', 'Narok', NULL, true, 185),
('Kisumu Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 186),
('Kisumu Kadhis Court', 'kadhi', false, 'Kisumu', 'Kisumu', NULL, true, 187),
('Kisumu SCC', 'small_claims', false, 'Kisumu', 'Kisumu', NULL, true, 188),
('Winam Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 189),
('Maseno Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 190),
('Nyando Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 191),
('Tamu Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 192),
('Kombewa Law Courts', 'magistrate', false, 'Kisumu', 'Kisumu', NULL, true, 193),
('Siaya Law Courts', 'magistrate', false, 'Siaya', 'Siaya', NULL, true, 194),
('Siaya SCC', 'small_claims', false, 'Siaya', 'Siaya', NULL, true, 195),
('Bondo Law Courts', 'magistrate', false, 'Siaya', 'Siaya', NULL, true, 196),
('Ukwala Law Courts', 'magistrate', false, 'Siaya', 'Siaya', NULL, true, 197),
('Madiany Law Courts', 'magistrate', false, 'Siaya', 'Siaya', NULL, true, 198),
('Kitui Law Courts', 'magistrate', false, 'Kitui', 'Kitui', NULL, true, 199),
('Kitui Kadhis Court', 'kadhi', false, 'Kitui', 'Kitui', NULL, true, 200),
('Kitui SCC', 'small_claims', false, 'Kitui', 'Kitui', NULL, true, 201),
('Mutomo Law Courts', 'magistrate', false, 'Kitui', 'Kitui', NULL, true, 202),
('Mwingi Law Courts', 'magistrate', false, 'Kitui', 'Kitui', NULL, true, 203),
('Kyuso Law Courts', 'magistrate', false, 'Kitui', 'Kitui', NULL, true, 204),
('Machakos Law Courts', 'magistrate', false, 'Machakos', 'Machakos', NULL, true, 205),
('Machakos Kadhis Court', 'kadhi', false, 'Machakos', 'Machakos', NULL, true, 206),
('Machakos SCC', 'small_claims', false, 'Machakos', 'Machakos', NULL, true, 207),
('Kithimani Law Courts', 'magistrate', false, 'Machakos', 'Machakos', NULL, true, 208),
('Kangundo Law Courts', 'magistrate', false, 'Machakos', 'Machakos', NULL, true, 209),
('Mavoko Law Courts', 'magistrate', false, 'Machakos', 'Machakos', NULL, true, 210),
('Wamunyu Law Courts', 'magistrate', false, 'Machakos', 'Machakos', NULL, true, 211),
('Makueni Law Courts', 'magistrate', false, 'Makueni', 'Makueni', NULL, true, 212),
('Tawa Law Courts', 'magistrate', false, 'Makueni', 'Makueni', NULL, true, 213),
('Kilungu Law Courts', 'magistrate', false, 'Makueni', 'Makueni', NULL, true, 214),
('Makindu Law Courts', 'magistrate', false, 'Makueni', 'Makueni', NULL, true, 215),
('Makindu SCC', 'small_claims', false, 'Makueni', 'Makueni', NULL, true, 216),
('Kajiado Law Courts', 'magistrate', false, 'Kajiado', 'Kajiado', NULL, true, 217),
('Kajiado Kadhis Court', 'kadhi', false, 'Kajiado', 'Kajiado', NULL, true, 218),
('Kajiado SCC', 'small_claims', false, 'Kajiado', 'Kajiado', NULL, true, 219),
('Loitoktok Law Courts', 'magistrate', false, 'Kajiado', 'Kajiado', NULL, true, 220),
('Loitoktok SCC', 'small_claims', false, 'Kajiado', 'Kajiado', NULL, true, 221),
('Ngong Law Courts', 'magistrate', false, 'Kajiado', 'Kajiado', NULL, true, 222),
('Malindi Law Courts', 'magistrate', false, 'Malindi', 'Kilifi', NULL, true, 223),
('Malindi Kadhis Court', 'kadhi', false, 'Malindi', 'Kilifi', NULL, true, 224),
('Malindi SCC', 'small_claims', false, 'Malindi', 'Kilifi', NULL, true, 225),
('Kilifi Law Courts', 'magistrate', false, 'Malindi', 'Kilifi', NULL, true, 226),
('Kilifi Kadhis Court', 'kadhi', false, 'Malindi', 'Kilifi', NULL, true, 227),
('Kaloleni Law Courts', 'magistrate', false, 'Malindi', 'Kilifi', NULL, true, 228),
('Mariakani Law Courts', 'magistrate', false, 'Malindi', 'Kilifi', NULL, true, 229),
('Mariakani Kadhis Court', 'kadhi', false, 'Malindi', 'Kilifi', NULL, true, 230),
('Garsen Law Courts', 'magistrate', false, 'Garsen', 'Tana River', NULL, true, 231),
('Garsen Kadhis Court', 'kadhi', false, 'Garsen', 'Tana River', NULL, true, 232),
('Hola Law Courts', 'magistrate', false, 'Garsen', 'Tana River', NULL, true, 233),
('Hola Kadhis Court', 'kadhi', false, 'Garsen', 'Tana River', NULL, true, 234),
('Lamu Law Courts', 'magistrate', false, 'Garsen', 'Lamu', NULL, true, 235),
('Lamu Kadhis Court', 'kadhi', false, 'Garsen', 'Lamu', NULL, true, 236),
('Lamu SCC', 'small_claims', false, 'Garsen', 'Lamu', NULL, true, 237),
('Mpeketoni Law Courts', 'magistrate', false, 'Garsen', 'Lamu', NULL, true, 238),
('Meru Law Courts', 'magistrate', false, 'Meru', 'Meru', NULL, true, 239),
('Meru Kadhis Court', 'kadhi', false, 'Meru', 'Meru', NULL, true, 240),
('Meru SCC', 'small_claims', false, 'Meru', 'Meru', NULL, true, 241),
('Nkubu Law Courts', 'magistrate', false, 'Meru', 'Meru', NULL, true, 242),
('Maua Law Courts', 'magistrate', false, 'Meru', 'Meru', NULL, true, 243),
('Tigania Law Courts', 'magistrate', false, 'Meru', 'Meru', NULL, true, 244),
('Githongo Law Courts', 'magistrate', false, 'Meru', 'Meru', NULL, true, 245),
('Isiolo Law Courts', 'magistrate', false, 'Meru', 'Isiolo', NULL, true, 246),
('Isiolo Kadhis Court', 'kadhi', false, 'Meru', 'Isiolo', NULL, true, 247),
('Garbatulla Kadhis Court', 'kadhi', false, 'Meru', 'Isiolo', NULL, true, 248),
('Merti Kadhis Court', 'kadhi', false, 'Meru', 'Isiolo', NULL, true, 249),
('Chuka Law Courts', 'magistrate', false, 'Chuka', 'Tharaka-Nithi', NULL, true, 250),
('Chuka SCC', 'small_claims', false, 'Chuka', 'Tharaka-Nithi', NULL, true, 251),
('Marimanti Law Courts', 'magistrate', false, 'Chuka', 'Tharaka-Nithi', NULL, true, 252),
('Marsabit Law Courts', 'magistrate', false, 'Marsabit', 'Marsabit', NULL, true, 253),
('Marsabit Kadhis Court', 'kadhi', false, 'Marsabit', 'Marsabit', NULL, true, 254),
('Moyale Law Courts', 'magistrate', false, 'Marsabit', 'Marsabit', NULL, true, 255),
('Moyale Kadhis Court', 'kadhi', false, 'Marsabit', 'Marsabit', NULL, true, 256),
('Moyale SCC', 'small_claims', false, 'Marsabit', 'Marsabit', NULL, true, 257),
('Migori Law Courts', 'magistrate', false, 'Migori', 'Migori', NULL, true, 258),
('Migori SCC', 'small_claims', false, 'Migori', 'Migori', NULL, true, 259),
('Rongo Law Courts', 'magistrate', false, 'Migori', 'Migori', NULL, true, 260),
('Kehancha Law Courts', 'magistrate', false, 'Migori', 'Migori', NULL, true, 261),
('Mombasa Law Courts', 'magistrate', false, 'Mombasa', 'Mombasa', NULL, true, 262),
('Mombasa SCC', 'small_claims', false, 'Mombasa', 'Mombasa', NULL, true, 263),
('Shanzu Law Courts', 'magistrate', false, 'Mombasa', 'Mombasa', NULL, true, 264),
('Tononoka Children''s Court', 'magistrate', false, 'Mombasa', 'Mombasa', 'Children''s Court division.', true, 265),
('Mombasa Kadhis Court', 'kadhi', false, 'Mombasa', 'Mombasa', NULL, true, 266),
('Msambweni Law Courts', 'magistrate', false, 'Kwale', 'Kwale', NULL, true, 267),
('Msambweni Kadhis Court', 'kadhi', false, 'Kwale', 'Kwale', NULL, true, 268),
('Kwale Law Court', 'magistrate', false, 'Kwale', 'Kwale', NULL, true, 269),
('Kwale Kadhis Court', 'kadhi', false, 'Kwale', 'Kwale', NULL, true, 270),
('Taveta Law Courts', 'magistrate', false, 'Voi', 'Taita-Taveta', NULL, true, 271),
('Taveta SCC', 'small_claims', false, 'Voi', 'Taita-Taveta', NULL, true, 272),
('Wundanyi Law Courts', 'magistrate', false, 'Voi', 'Taita-Taveta', NULL, true, 273),
('Voi Law Courts', 'magistrate', false, 'Voi', 'Taita-Taveta', NULL, true, 274),
('Voi Kadhis Court', 'kadhi', false, 'Voi', 'Taita-Taveta', NULL, true, 275),
('Murang''a Law Courts', 'magistrate', false, 'Murang''a', 'Murang''a', NULL, true, 276),
('Murang''a SCC', 'small_claims', false, 'Murang''a', 'Murang''a', NULL, true, 277),
('Kangema Law Courts', 'magistrate', false, 'Murang''a', 'Murang''a', NULL, true, 278),
('Kigumo Law Courts', 'magistrate', false, 'Murang''a', 'Murang''a', NULL, true, 279),
('Kandara Law Courts', 'magistrate', false, 'Murang''a', 'Murang''a', NULL, true, 280),
('Kenol Law Courts', 'magistrate', false, 'Murang''a', 'Murang''a', NULL, true, 281),
('Milimani Law Courts', 'magistrate', false, 'Nairobi', 'Nairobi', NULL, true, 282),
('Milimani Children''s Court', 'magistrate', false, 'Nairobi', 'Nairobi', 'Children''s Court division.', true, 283),
('Milimani Anti-Corruption Court', 'magistrate', false, 'Nairobi', 'Nairobi', 'Anti-Corruption and Economic Crimes division.', true, 284),
('Nairobi City County Law Courts', 'magistrate', false, 'Nairobi', 'Nairobi', NULL, true, 285),
('Milimani Commercial - Commercial & Civil Div.', 'magistrate', false, 'Nairobi', 'Nairobi', 'Commercial division.', true, 286),
('Milimani Commercial - Family & Divorce Div.', 'magistrate', false, 'Nairobi', 'Nairobi', 'Commercial division.', true, 287),
('Milimani Small Claims Court', 'small_claims', false, 'Nairobi', 'Nairobi', NULL, true, 288),
('Makadara Law Courts', 'magistrate', false, 'Nairobi', 'Nairobi', NULL, true, 289),
('JKIA Law Courts', 'magistrate', false, 'Nairobi', 'Nairobi', NULL, true, 290),
('Upperhill Kadhis Court', 'kadhi', false, 'Nairobi', 'Nairobi', NULL, true, 291),
('Kibera Law Courts', 'magistrate', false, 'Kibera', 'Nairobi', NULL, true, 292),
('Kibera Kadhis Court', 'kadhi', false, 'Kibera', 'Nairobi', NULL, true, 293),
('Kahawa Law Courts', 'magistrate', false, 'Kibera', 'Nairobi', NULL, true, 294),
('Dagoretti Law Courts', 'magistrate', false, 'Kibera', 'Nairobi', NULL, true, 295),
('Dagoretti SCC', 'small_claims', false, 'Kibera', 'Nairobi', NULL, true, 296),
('Kiambu Law Courts', 'magistrate', false, 'Kiambu', 'Kiambu', NULL, true, 297),
('Kikuyu Law Courts', 'magistrate', false, 'Kiambu', 'Kiambu', NULL, true, 298),
('Limuru Law Courts', 'magistrate', false, 'Kiambu', 'Kiambu', NULL, true, 299),
('Githunguri Law Courts', 'magistrate', false, 'Kiambu', 'Kiambu', NULL, true, 300),
('Thika Law Courts', 'magistrate', false, 'Thika', 'Kiambu', NULL, true, 301),
('Thika SCC', 'small_claims', false, 'Thika', 'Kiambu', NULL, true, 302),
('Gatundu Law Courts', 'magistrate', false, 'Thika', 'Kiambu', NULL, true, 303),
('Ruiru Law Courts', 'magistrate', false, 'Thika', 'Kiambu', NULL, true, 304),
('Ruiru SCC', 'small_claims', false, 'Thika', 'Kiambu', NULL, true, 305),
('Kamwangi Law Courts', 'magistrate', false, 'Thika', 'Kiambu', NULL, true, 306),
('Nakuru Law Courts', 'magistrate', false, 'Nakuru', 'Nakuru', NULL, true, 307),
('Nakuru Kadhis Court', 'kadhi', false, 'Nakuru', 'Nakuru', NULL, true, 308),
('Nakuru SCC', 'small_claims', false, 'Nakuru', 'Nakuru', NULL, true, 309),
('Molo Law Courts', 'magistrate', false, 'Nakuru', 'Nakuru', NULL, true, 310),
('Naivasha Law Courts', 'magistrate', false, 'Naivasha', 'Nakuru', NULL, true, 311),
('Naivasha SCC', 'small_claims', false, 'Naivasha', 'Nakuru', NULL, true, 312),
('Engineer Law Courts', 'magistrate', false, 'Nyandarua', 'Nyandarua', NULL, true, 313),
('Ol Kalou Law Courts', 'magistrate', false, 'Nyandarua', 'Nyandarua', NULL, true, 314),
('Eldama Ravine Law Courts', 'magistrate', false, 'Kabarnet', 'Baringo', NULL, true, 315),
('Kabarnet Law Courts', 'magistrate', false, 'Kabarnet', 'Baringo', NULL, true, 316),
('Nyahururu Law Courts', 'magistrate', false, 'Nyahururu', 'Laikipia', NULL, true, 317),
('Nanyuki Law Courts', 'magistrate', false, 'Nanyuki', 'Laikipia', NULL, true, 318),
('Nanyuki SCC', 'small_claims', false, 'Nanyuki', 'Laikipia', NULL, true, 319),
('Rumuruti Law Courts', 'magistrate', false, 'Nanyuki', 'Laikipia', NULL, true, 320),
('Maralal Law Courts', 'magistrate', false, 'Nanyuki', 'Samburu', NULL, true, 321),
('Nyeri Law Courts', 'magistrate', false, 'Nyeri', 'Nyeri', NULL, true, 322),
('Nyeri Kadhis Court', 'kadhi', false, 'Nyeri', 'Nyeri', NULL, true, 323),
('Nyeri SCC', 'small_claims', false, 'Nyeri', 'Nyeri', NULL, true, 324),
('Othaya Law Courts', 'magistrate', false, 'Nyeri', 'Nyeri', NULL, true, 325),
('Karatina Law Courts', 'magistrate', false, 'Nyeri', 'Nyeri', NULL, true, 326),
('Mukurwe-ini Law Courts', 'magistrate', false, 'Nyeri', 'Nyeri', NULL, true, 327);
